"""Rules with a published deep-dive page under docs/rules/.

GENERATED by scripts/sync_rule_doc_pages.py -- do not edit by hand.

SARIF helpUri deep-links a rule only when its page exists; every other rule
points at the rules index, which resolves. See the script's docstring for why
the alternative (deep-link everything) is worse than it looks.
"""

from __future__ import annotations

RULE_DOC_PAGES: frozenset[str] = frozenset({
    "AAK-AZURE-MCP-001",
    "AAK-AZURE-MCP-NOAUTH-001",
    "AAK-LANGCHAIN-SSRF-REDIR-001",
    "AAK-LMDEPLOY-VL-SSRF-001",
    "AAK-MCP-AUTH-PATHTRAVERSAL-001",
    "AAK-MCP-MARKETPLACE-CONFIG-FETCH-001",
    "AAK-MCP-STDIO-CMD-INJ-001",
    "AAK-MCP-STDIO-CMD-INJ-002",
    "AAK-MCP-STDIO-CMD-INJ-003",
    "AAK-MCP-STDIO-CMD-INJ-004",
    "AAK-SPLUNK-MCP-TOKEN-LEAK-001",
    "AAK-SSRF-TOCTOU-001",
    "AAK-TOXICFLOW-001",
})
