#!/usr/bin/env python3
"""Guard: a governed report figure may not appear outside a ``report:`` marker.

``tests/test_report_headline_numbers.py`` locks every ``<!-- report:key -->``
marker to ``results.json``. It is a strong guard with one blind spot that is
structural rather than accidental: it can only see numbers that already carry a
marker. A second, unmarked copy of the same figure is invisible to it, and an
unmarked copy is precisely what a person writing prose produces.

That blind spot is not hypothetical. When this script was written, four
published sites stated ``100% (421/421)`` and ``421 / 18.3%`` while
``results.json`` said 424 and 18.4% — and the marker test was green, because
none of the four carried a marker:

    README.md:55                            100% (421/421) of inline-auth …
    README.md:573                           100% (421/421) of inline-auth …
    docs/STATE-OF-MCP-SECURITY-2026.md:36   100% (421/421) of inline-auth …
    research/state-of-mcp-2026/PREVALENCE.md:95   | … | 421 | 18.3% |

The last of those contradicted ``REPORT.md`` line 37 — 18.4% (424) — inside the
same directory.

How the matching is scoped, and why
-----------------------------------
The obvious implementation is "no bare integer outside a marker". It is also
useless: it fires on every rule ID, CVE year, RFC number, version string and
table row in the tree, and a guard that cries wolf is switched off within a
week. A first draft of this file did exactly that — an un-anchored ``N% (M)``
pattern matched all nine rows of REPORT.md's top-misconfiguration table.

So each governed figure gets a pattern anchored to the *claim it appears in*,
not to its digits: the inline-auth ratio is only recognised next to the words
"of inline-auth", the AAK-OAUTH-008 row only next to that rule ID. The pattern
set fires on the four sites above and nowhere else in the tree.

Marker contents are masked before scanning — digits inside a marker span are
replaced in place with ``#``, preserving every byte offset so reported line
numbers stay exact. A correctly marked figure therefore has no digits left to
match, and cannot be reported.

Two file modes
--------------
``MUST_BE_MARKED``  README, the coverage doc and PREVALENCE.md are generated by
                    ``scripts/sync_rule_count.py``. Any governed figure outside
                    a marker is a defect there even when its value is currently
                    right, because nothing will update it when the data moves.

``MUST_AGREE``      REPORT.md is the source document. Its prose is asserted by
                    ``test_report_headline_numbers.py`` rather than generated —
                    it is the thing the markers are pinned *to* — so an unmarked
                    figure there is expected. What is not expected is one that
                    disagrees with the data, so only a wrong value is reported.
                    This is how the AAK-OAUTH-008 figure in REPORT.md becomes
                    governed at all; no other test reads it.

Single source of truth for two callers:
    - tests/test_report_unmarked_figures.py
    - Makefile `report-figures-check`, run in CI beside `count-check`

Usage:
    python scripts/check_report_figures.py
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

# Any complete marker span. Masked before scanning so a marked figure is invisible.
_MARKER_SPAN = re.compile(
    r"<!--\s*report:[a-z0-9-]+\s*-->.*?<!--\s*/report\s*-->", re.DOTALL
)

MUST_BE_MARKED = (
    "README.md",
    "docs/STATE-OF-MCP-SECURITY-2026.md",
    "research/state-of-mcp-2026/PREVALENCE.md",
)
MUST_AGREE = ("research/state-of-mcp-2026/REPORT.md",)


@dataclass(frozen=True)
class Figure:
    """One governed claim, and the shape it is written in.

    ``expected`` maps the pattern's capture groups (in order) to the governed
    key whose value that group must equal.
    """

    name: str
    pattern: "re.Pattern[str]"
    keys: tuple[str, ...]


FIGURES: tuple[Figure, ...] = (
    Figure(
        # "100% (424/424) of inline-auth remote configs …". The `of inline-auth`
        # anchor is what keeps this off every other percentage in the tree, and
        # \s+ spans the line break the coverage doc puts between ")" and "inline".
        name="inline-auth static-credential ratio",
        pattern=re.compile(
            r"(\d+(?:\.\d+)?)%\s*\((\d[\d,]*)\s*/\s*(\d[\d,]*)\)\**\s*of\s+inline-auth",
            re.IGNORECASE,
        ),
        keys=("inline-auth-pct", "inline-auth-n", "inline-auth-d"),
    ),
    Figure(
        # PREVALENCE.md's top-10 row: "| … | LOW | 424 | 18.4% |".
        name="AAK-OAUTH-008 prevalence row (count, share)",
        pattern=re.compile(
            r"AAK-OAUTH-008[^\n]*?\|\s*(\d[\d,]*)\s*\|\s*(\d+(?:\.\d+)?)%\s*\|"
        ),
        keys=("oauth008-n", "oauth008-pct"),
    ),
    Figure(
        # REPORT.md writes the same row the other way round: "| 18.4% (424) |".
        name="AAK-OAUTH-008 report row (share, count)",
        pattern=re.compile(r"AAK-OAUTH-008[^\n]*?(\d+(?:\.\d+)?)%\s*\((\d[\d,]*)\)"),
        keys=("oauth008-pct", "oauth008-n"),
    ),
    Figure(
        # The metric that actually rotted in 2026-08: "52.1% (1,200) declare a
        # remote server with no authentication". Anchored to the claim, so it
        # does not match the eight sibling rows of the same table.
        name="no-authentication share",
        pattern=re.compile(
            r"(\d+(?:\.\d+)?)%\s*\((\d[\d,]*)(?:\s*/\s*[\d,]+)?\)[^\n]{0,60}?"
            r"(?:declare a remote server with no auth|with no authentication"
            r"|without authentication)",
            re.IGNORECASE,
        ),
        keys=("noauth-pct", "noauth-n"),
    ),
)


def mask_markers(text: str) -> str:
    """Replace digits inside marker spans with ``#``, preserving all offsets.

    Length-preserving on purpose: line numbers are computed from offsets in the
    masked text and must point at the real line in the real file.
    """
    return _MARKER_SPAN.sub(lambda m: re.sub(r"\d", "#", m.group(0)), text)


def _num(raw: str) -> float:
    return float(raw.replace(",", ""))


def governed_values() -> dict[str, float]:
    """Canonical value per key, from the generator -- not re-derived here.

    Importing rather than re-reading results.json keeps one definition of what a
    key means; a second reader would be the very duplication this guards.
    """
    from sync_rule_count import report_headline_numbers  # noqa: PLC0415

    return {k: _num(v) for k, v in report_headline_numbers().items()}


def scan_file(rel: str, *, must_be_marked: bool,
              values: Optional[dict[str, float]] = None) -> list[str]:
    """``file:line  …`` for every violation in one file."""
    path = REPO_ROOT / rel
    if not path.is_file():
        return []
    values = values if values is not None else governed_values()
    text = mask_markers(path.read_text(encoding="utf-8"))
    out: list[str] = []

    for figure in FIGURES:
        for match in figure.pattern.finditer(text):
            line = text[: match.start()].count("\n") + 1
            found = [_num(g) for g in match.groups()]
            want = [values[k] for k in figure.keys]
            agrees = found == want

            if must_be_marked:
                state = "matches results.json but is not marker-driven" if agrees \
                    else f"disagrees with results.json (data says {want})"
                out.append(
                    f"{rel}:{line}  {figure.name}: found {found}, {state}"
                )
            elif not agrees:
                out.append(
                    f"{rel}:{line}  {figure.name}: found {found}, "
                    f"results.json says {want}"
                )
    return out


def find_violations() -> tuple[list[str], list[str]]:
    """(unmarked-copy violations, disagreement violations)."""
    values = governed_values()
    unmarked = [
        row for rel in MUST_BE_MARKED
        for row in scan_file(rel, must_be_marked=True, values=values)
    ]
    disagree = [
        row for rel in MUST_AGREE
        for row in scan_file(rel, must_be_marked=False, values=values)
    ]
    return unmarked, disagree


def main(argv: Optional[list[str]] = None) -> int:
    unmarked, disagree = find_violations()

    if unmarked:
        print(
            f"::error ::report-figures: {len(unmarked)} governed figure(s) stated "
            f"outside a `report:` marker. Wrap each in the marker pair "
            f"scripts/sync_rule_count.py already owns, then run `make report`. "
            f"A hand-typed correct value is the same defect as a stale one:",
            file=sys.stderr,
        )
        for row in unmarked:
            print(f"  {row}", file=sys.stderr)

    if disagree:
        print(
            f"::error ::report-figures: {len(disagree)} figure(s) in the source "
            f"report disagree with results.json. REPORT.md is prose-asserted "
            f"rather than generated, so fix the prose or regenerate the data:",
            file=sys.stderr,
        )
        for row in disagree:
            print(f"  {row}", file=sys.stderr)

    if unmarked or disagree:
        return 1

    print(
        f"report-figures: clean — no governed figure stated outside a marker "
        f"across {len(MUST_BE_MARKED)} generated surface(s), and "
        f"{len(MUST_AGREE)} source document(s) agree with results.json."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
