#!/usr/bin/env python3
"""Auto-generate docs/owasp-agentic-coverage.md.

Walks `agent_audit_kit.rules.builtin.RULES` and writes one row per
OWASP Agentic Top 10 2026 entry (ASI01…ASI10) with the rule IDs that
tag it. Missing slots fail loudly — the corresponding pytest is the
regression fence.

Run locally or from CI (planned in `sync-rule-count.yml`).
"""

from __future__ import annotations

import pathlib
import sys
from collections import defaultdict


REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
DOC_PATH = REPO_ROOT / "docs" / "owasp-agentic-coverage.md"
README_PATH = REPO_ROOT / "README.md"

_MARKER_START = "<!-- owasp-coverage:start -->"
_MARKER_END = "<!-- owasp-coverage:end -->"

# Canonical OWASP Agentic Top 10 2026 titles. Source:
# https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications-for-2026/
ASI_TITLES: dict[str, str] = {
    "ASI01": "Goal Hijack",
    "ASI02": "Tool Misuse",
    "ASI03": "Memory Poisoning",
    "ASI04": "Identity & Privilege Abuse",
    "ASI05": "Cascading Failures",
    "ASI06": "Unauthorized Capability Acquisition",
    "ASI07": "Plan Injection",
    "ASI08": "Agent Communication Poisoning",
    "ASI09": "Resource Abuse",
    "ASI10": "Supply-Chain",
}


def build_coverage() -> dict[str, list[str]]:
    from agent_audit_kit.rules.builtin import RULES

    cov: dict[str, list[str]] = defaultdict(list)
    for rid, rule in sorted(RULES.items()):
        for asi in rule.owasp_agentic_references:
            cov[asi].append(rid)
    return dict(cov)


def render_markdown(coverage: dict[str, list[str]]) -> str:
    lines: list[str] = [
        "# OWASP Top 10 for Agentic Applications — 2026 coverage",
        "",
        "Auto-generated by `scripts/gen_owasp_coverage.py`. Every AAK rule "
        "that claims an `ASI<nn>` reference lands in the corresponding row. "
        "`tests/test_owasp_agentic_coverage.py` is the regression fence — "
        "it fails CI if any row has zero rules.",
        "",
        "Source: <https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications-for-2026/>",
        "",
        "| ASI | Title | # rules | Rule IDs |",
        "| --- | --- | --- | --- |",
    ]
    for asi in sorted(ASI_TITLES):
        rules = coverage.get(asi, [])
        title = ASI_TITLES[asi]
        rule_text = ", ".join(f"`{r}`" for r in rules) or "_no rules — CI will fail_"
        lines.append(f"| **{asi}** | {title} | {len(rules)} | {rule_text} |")
    lines.append("")
    return "\n".join(lines)


def render_readme_snippet(coverage: dict[str, list[str]]) -> str:
    """Compact summary suitable for the README marker block."""
    lines = ["| ASI | Title | # rules |", "| --- | --- | --- |"]
    for asi in sorted(ASI_TITLES):
        rules = coverage.get(asi, [])
        lines.append(f"| **{asi}** | {ASI_TITLES[asi]} | {len(rules)} |")
    return "\n".join(lines)


def _update_readme_marker(snippet: str) -> bool:
    if not README_PATH.is_file():
        return False
    text = README_PATH.read_text(encoding="utf-8")
    if _MARKER_START not in text or _MARKER_END not in text:
        return False
    before, _, rest = text.partition(_MARKER_START)
    _, _, after = rest.partition(_MARKER_END)
    rebuilt = (
        f"{before}{_MARKER_START}\n{snippet}\n{_MARKER_END}{after}"
    )
    if rebuilt != text:
        README_PATH.write_text(rebuilt, encoding="utf-8")
        return True
    return False


def main() -> int:
    coverage = build_coverage()
    missing = [asi for asi in ASI_TITLES if not coverage.get(asi)]
    text = render_markdown(coverage)
    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text(text, encoding="utf-8")
    sys.stdout.write(f"wrote {DOC_PATH} ({len(text)} bytes)\n")
    if _update_readme_marker(render_readme_snippet(coverage)):
        sys.stdout.write(f"updated README.md owasp-coverage marker\n")
    if missing:
        sys.stderr.write(
            "coverage gap: no rules tag "
            + ", ".join(missing)
            + ". Add at least one rule in agent_audit_kit/rules/builtin.py.\n"
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
