#!/usr/bin/env python3
"""Regenerate ``agent_audit_kit/output/_rule_doc_pages.py`` from ``docs/rules/``.

SARIF ``helpUri`` has to resolve. Until 2026-09-05 it pointed every rule at
``https://agent-audit-kit.dev/rules/<id>``, on a domain that has never been
registered (NXDOMAIN, no NS/A/MX), so every "more info" link in the GitHub
Security tab was dead.

Pointing them all at the published docs site instead would have been the obvious
fix and is only half right: 14 of 332 rules have a hand-written deep-dive page,
and the other 318 do not. A per-rule URL for all of them trades one link that
fails uniformly for one that fails 96% of the time, which is strictly harder to
notice.

So the base URL is the published rules index, which resolves for every rule, and
a rule is deep-linked only when its page actually exists. This script freezes
that set into the package, because ``docs/`` is not shipped in the wheel
(``packages = ["agent_audit_kit"]``) and the formatter therefore cannot look on
disk at scan time.

Adding ``docs/rules/AAK-FOO-001.md`` and re-running this upgrades that rule's
helpUri automatically. ``tests/test_rule_doc_pages_sync.py`` fails when the two
drift.

Usage:
    python scripts/sync_rule_doc_pages.py            # rewrite the constant
    python scripts/sync_rule_doc_pages.py --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS_RULES = REPO_ROOT / "docs" / "rules"
TARGET = REPO_ROOT / "agent_audit_kit" / "output" / "_rule_doc_pages.py"

# Pages under docs/rules/ that are not a single rule's deep dive.
_NOT_A_RULE = {"index", "skill-composition"}

_HEADER = '''"""Rules with a published deep-dive page under docs/rules/.

GENERATED by scripts/sync_rule_doc_pages.py -- do not edit by hand.

SARIF helpUri deep-links a rule only when its page exists; every other rule
points at the rules index, which resolves. See the script's docstring for why
the alternative (deep-link everything) is worse than it looks.
"""

from __future__ import annotations

RULE_DOC_PAGES: frozenset[str] = frozenset({
'''

_FOOTER = "})\n"


def discovered() -> list[str]:
    """Rule ids with a deep-dive page, sorted."""
    if not DOCS_RULES.is_dir():
        return []
    return sorted(
        path.stem
        for path in DOCS_RULES.glob("*.md")
        if path.stem not in _NOT_A_RULE
    )


def render(rule_ids: list[str]) -> str:
    body = "".join(f'    "{rule_id}",\n' for rule_id in rule_ids)
    return _HEADER + body + _FOOTER


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Exit 1 if stale.")
    args = parser.parse_args(argv)

    rule_ids = discovered()
    want = render(rule_ids)
    have = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""

    if want == have:
        print(f"sync_rule_doc_pages: clean ({len(rule_ids)} deep-dive pages).")
        return 0

    if args.check:
        print(
            "::error ::sync_rule_doc_pages: _rule_doc_pages.py is stale. "
            "Run `python scripts/sync_rule_doc_pages.py` and commit the result.",
            file=sys.stderr,
        )
        return 1

    TARGET.write_text(want, encoding="utf-8")
    print(f"sync_rule_doc_pages: wrote {len(rule_ids)} deep-dive page ids.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
