#!/usr/bin/env python3
"""Render the README false-positive badge from the benchmark's own artifacts.

The badge used to be a hand-typed literal, and it drifted exactly the way
hand-typed numbers do: the corpus manifest grew 1,374 -> 1,641 servers, the
benign slice grew 368 -> 536, nobody re-ran the benchmark, and the README went on
advertising a rate measured against a slice that no longer existed.

It also *read* wrong. ``0/1 (n=1)`` parses as "one thing was tested". What it
meant was "368 configs were scanned and exactly one high-severity finding came
out of them". Two different numbers, and the badge only showed the one that made
the sample look tiny. Both are rendered now.

Sources, neither of which this script may edit:

  * ``benchmarks/false_positive/results.json`` - machine-generated by ``run.py``;
    supplies the slice size.
  * ``benchmarks/false_positive/adjudication.json`` - the human verdicts. The
    harness deliberately does not label its own findings, so the false-positive
    *rate* cannot be derived from ``results.json`` alone.

Usage::

    python scripts/sync_fp_badge.py            # rewrite the badge in README.md
    python scripts/sync_fp_badge.py --check    # exit 1 if the badge is stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from urllib.parse import quote

REPO_ROOT = Path(__file__).resolve().parent.parent
README = REPO_ROOT / "README.md"
RESULTS = REPO_ROOT / "benchmarks" / "false_positive" / "results.json"
ADJUDICATION = REPO_ROOT / "benchmarks" / "false_positive" / "adjudication.json"

START = "<!-- fp-badge -->"
END = "<!-- /fp-badge -->"
_BLOCK_RE = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)

# Rate thresholds -> shields colour. Deliberately not flattering: a
# two-thirds false-positive rate should not render green because the badge
# would then be decoration rather than a measurement.
_COLOURS = ((0.05, "brightgreen"), (0.15, "green"), (0.35, "yellow"), (0.60, "orange"))
_WORST = "red"


def _colour(rate: float) -> str:
    for threshold, name in _COLOURS:
        if rate <= threshold:
            return name
    return _WORST


def badge_markup(slice_n: int, false_positives: int, adjudicated: int) -> str:
    """The full anchor+img block, including the enclosing markers."""
    rate = (false_positives / adjudicated) if adjudicated else 0.0
    # "MCP configs", not "configs": the slice is MCP server configs only. Bare
    # "configs" read as covering instruction files too, which this benchmark
    # never measures (AAK-AGENT-002 on CLAUDE.md / AGENTS.md was found outside it).
    label = f"benign-slice {slice_n} MCP configs"
    message = f"HIGH/CRIT FP {false_positives}/{adjudicated}"
    # shields.io: a literal dash in a label/message is escaped by doubling it, and
    # `/` must be percent-encoded or it is read as a path separator and splits the
    # badge into the wrong fields. `quote` defaults to `safe="/"`, so the empty
    # `safe` here is load-bearing rather than tidiness.
    src = (
        "https://img.shields.io/badge/"
        f"{quote(label.replace('-', '--'), safe='')}-"
        f"{quote(message.replace('-', '--'), safe='')}-"
        f"{_colour(rate)}.svg"
    )
    alt = (
        f"Benign-slice false-positive measurement: {slice_n} MCP configs scanned, "
        f"{false_positives} of {adjudicated} HIGH/CRITICAL findings were false "
        f"positives ({rate * 100:.1f}%)"
    )
    return (
        f'{START}<a href="benchmarks/false_positive/RESULTS.md">'
        f'<img src="{src}" alt="{alt}"></a>{END}'
    )


def current_numbers() -> tuple[int, int, int]:
    """``(slice_n, false_positives, adjudicated)`` from the benchmark artifacts."""
    results = json.loads(RESULTS.read_text(encoding="utf-8"))
    adj = json.loads(ADJUDICATION.read_text(encoding="utf-8"))
    verdicts = adj.get("verdicts") or []
    fps = sum(1 for v in verdicts if v.get("verdict") == "false_positive")
    return int(results["benign_slice_n"]), fps, len(verdicts)


def render(check: bool = False) -> int:
    slice_n, fps, adjudicated = current_numbers()
    if adjudicated == 0:
        print("adjudication.json records no verdicts - nothing to render", file=sys.stderr)
        return 1

    text = README.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print(
            f"README.md has no {START} ... {END} block; add the markers around the "
            "false-positive badge so it can be generated rather than hand-typed",
            file=sys.stderr,
        )
        return 1

    want = badge_markup(slice_n, fps, adjudicated)
    updated = _BLOCK_RE.sub(lambda _: want, text, count=1)

    if check:
        if updated != text:
            print(
                "README false-positive badge is stale - run "
                "'make fp' and commit.\n"
                f"  expected: {want}",
                file=sys.stderr,
            )
            return 1
        print(
            f"fp badge is up to date (slice n = {slice_n}, "
            f"FP {fps}/{adjudicated})"
        )
        return 0

    if updated != text:
        README.write_text(updated, encoding="utf-8")
        print(f"updated README fp badge (slice n = {slice_n}, FP {fps}/{adjudicated})")
    else:
        print("fp badge already current")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check", action="store_true", help="Exit 1 if the badge is stale."
    )
    args = ap.parse_args(sys.argv[1:] if argv is None else argv)
    return render(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
